Traceback (most recent call last):
  File "C:\Users\sofmo\miniconda3\envs\EDA\lib\site-packages\nbclient\client.py", line 782, in _async_poll_for_reply
    msg = await ensure_async(self.kc.shell_channel.get_msg(timeout=new_timeout))
  File "C:\Users\sofmo\miniconda3\envs\EDA\lib\site-packages\jupyter_core\utils\__init__.py", line 198, in ensure_async
    result = await obj
  File "C:\Users\sofmo\miniconda3\envs\EDA\lib\site-packages\jupyter_client\channels.py", line 230, in get_msg
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sofmo\miniconda3\envs\EDA\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\sofmo\miniconda3\envs\EDA\lib\site-packages\nbclient\client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\sofmo\miniconda3\envs\EDA\lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "C:\Users\sofmo\miniconda3\envs\EDA\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\sofmo\miniconda3\envs\EDA\lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Users\sofmo\miniconda3\envs\EDA\lib\site-packages\nbclient\client.py", line 1005, in async_execute_cell
    exec_reply = await self.task_poll_for_reply
  File "C:\Users\sofmo\miniconda3\envs\EDA\lib\site-packages\nbclient\client.py", line 806, in _async_poll_for_reply
    error_on_timeout_execute_reply = await self._async_handle_timeout(timeout, cell)
  File "C:\Users\sofmo\miniconda3\envs\EDA\lib\site-packages\nbclient\client.py", line 856, in _async_handle_timeout
    raise CellTimeoutError.error_from_timeout_and_cell(
nbclient.exceptions.CellTimeoutError: A cell timed out while it was being executed, after 30 seconds.
The message was: Cell execution timed out.
Here is a preview of the cell contents:
-------------------
knn_metrics = [evaluate_model(model['model'], X_test, y_test) for model in knn_models]
knn_metrics_df = DataFrame(knn_metrics, index=[model['name'] for model in knn_models])
display(knn_metrics_df)
-------------------

